name: Selenium Capstone Tests with Allure & HTML Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html pytest-metadata allure-pytest selenium requests

      # 4️⃣ Run Pytest with Allure + HTML report generation
      - name: Run Pytest (Allure + HTML)
        run: |
          mkdir -p reports allure-results
          pytest -s tests --alluredir=allure-results --html=reports/report.html --self-contained-html

      # 5️⃣ Generate Allure HTML report
      - name: Generate Allure HTML report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_reports: 5

      # 6️⃣ Upload HTML Report (pytest-html)
      - name: Upload Pytest HTML report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/report.html

      # 7️⃣ Upload Allure Report
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
