name: Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html allure-pytest selenium webdriver-manager

      # 4️⃣ Run tests with HTML and Allure reports
      - name: Run Selenium tests
        run: |
          mkdir -p reports allure-results
          pytest -s tests --html=reports/report.html --alluredir=allure-results || true

      # 5️⃣ Upload HTML report
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: reports/report.html

      # 6️⃣ Upload Allure results
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results

      # 7️⃣ (Optional) Generate Allure report for GitHub Pages or preview
      # You can add allure report generation in a separate job if needed
